balena-os/balena-jetson

- jetson-nano.coffee
Otherwise the ImageMaker cannot get the right partition for the
configuration.
Changelog-entry: Fix primary partition number
Signed-off-by: Gergely Imreh <gergely@balena.io>
> device-type: fix primary partition number

- jetson-xavier.coffee
Update meta-balena from 2.37.0 to 2.38.0
Changelog-entry: Update the meta-balena submodule from v2.37.0 to v2.38.0
> layers/meta-balena: Update meta-balena to v2.38.0

- jetson-xavier.coffee
Currently the xavier is marked as community,
but support for it was added by Balena.
Switch this board to BETA.
Changelog-entry: jetson-xavier: Switch to BETA
> jetson-xavier: Switch to BETA

- layers/meta-balena-jetson/recipes-bsp/u-boot/u-boot-tegra/load-extlinux.conf-and-kernel-from-root-partit.patch
- layers/meta-balena-jetson/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
- layers/meta-balena-jetson/recipes-core/images/resin-image.inc
This fixes rollback-altboot issues where board won't get online after a failed HUP to a version that contains a kernel update: https://github.com/balena-os/balena-jetson/issues/17
A separate PR will be done for the TX2 which, unlinke the nano, uses the uboot from emmc when loading a flasher image from the sd-card.
> jetson-nano: load kernel from rootfs

- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra/nano-mark-gpio-as-disabled-when-freed.patch
- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
This patch fixes issues if SPI is enabled
during flashing.
Changelog-entry: linux-tegra: Fix hang on Nano during flash if SPI enabled
> linux-tegra: Fix hang on Nano during flash if SPI enabled

- jetson-nano.coffee
- jetson-tx2.coffee
- jetson-xavier.coffee
- jn30b-nano.coffee
- n510-tx2.coffee
- orbitty-tx2.coffee
- spacely-tx2.coffee
Board states have changed meanwhile in the old repository, like in the case for TX2. Others have only switched to 'new'.
> Update board states

- layers/meta-balena-jetson/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
- layers/meta-balena-jetson/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
Customer request to add firmware for the Intel 9260 wifi
adapter
Changelog-entry: Add firmware for the Intel 9260 wifi adapter
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>
> linux-firmware: Add firmware for the Intel 9260 wifi chipset

- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra/0001-cti-photon-nano-merge-MMC-driver-changes-from-BSP.patch
- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
This is a refactor of #62
Add kernel changes for CTI photon nano [as mentioned by @dremsol][1]
- MMC driver patch for SD reader support
- defconfig addition for RGB LED driver support
These changes come from CTI's BSP.
Source: http://connecttech.com/ftp/dropbox/cti-l4t-src-nano-32.3.1-v001.tgz
[1]: https://github.com/balena-os/balena-jetson/pull/60#issuecomment-619890028
> CTI photon-nano kernel patches v2

- layers/meta-balena-jetson/recipes-core/images/resin-image-flasher.bbappend
- layers/meta-balena-jetson/recipes-core/images/resin-image.inc
Update the meta-balena version to be in sync with the one that had the common tests ran for the RPI ESR.
> Updates 2020.07.x

- layers/meta-balena-jetson/recipes-core/images/resin-image.inc
BalenaOS is now preparing a solution for overlaying extra
content in the rootfs for any device type so let's install the
nvidia hook, csv and dependencies for all the boards in this
repository.
> Install hooks and dependencies for all Jetson devices

- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
tx2-6 custom dtb was missing from boot directory,
let's add it there.
Also, switched some built-in input drivers to modules
to save some space in the boot part for flasher images.
Changelog-entry: linux-tegra: Install custom options 6 dtb in rootfs
> linux-tegra: Install custom options 6 dtb in rootfs

- layers/meta-balena-jetson/conf/machine/photon-xavier-nx.conf
work-around for OE4T/meta-tegra#400 for photon-xavier-nx.
closes #111
> fix machine overrides for photon-xavier-nx

- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/50-resin-bootfiles-jetson-tx2
- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-nano
- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-xavier
- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-xavier-nx-devkit-emmc
We want to preserve current flashed odmdata for the device that supports this currently, Jetson TX2, to prevent the case where the supervisor had already set a odm value which then gets overridden during HUP. This would trigger the supervisor to reboot the board before HUP is completed.
Also, usually partitions have their nonces updated during each build, but we should ensure however which do and which don't need the update.
Addresses: https://github.com/balena-os/balena-jetson/issues/103
Do not merge until tested on all boards.
> Preserve odm value during hup TX2, check where partitions need updating

- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
Changelog-entry: linux-tegra: Add gasket driver for Jetson Nano
> linux-tegra: Add gasket driver for Jetson Nano

- layers/meta-balena-jetson/classes/features_check.bbclass
- layers/meta-balena-jetson/conf/layer.conf
* Masquerade the features_check class in Dunfell as distro_features_check to be able to build recipes from meta-tegra that use it
* Modify BBMASK to allow to build some meta-tegra/recipes-graphics recipes
Connects to: https://github.com/balena-os/balena-yocto-scripts/pull/177
Connects-to: https://github.com/balena-os/meta-balena/pull/1987
> Allow to build tegra libraries recipes

- layers/meta-balena-jetson/recipes-core/images/resin-image.inc
This is present in the official image for the NX Devkit,
let's add it our image too.
Changelog-entry: resin-image: Install tegra-udrm probeconf file for NX Devkit
> resin-image: Install tegra-udrm probeconf file for NX Devkit

- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bbappend
Changelog-entry: hostapp-update-hooks: Add hooks for Nano 2GB
> hostapp-update-hooks: Add hooks for Nano 2GB

- layers/meta-balena-jetson/recipes-containers/nvidia-container-runtime/nvidia-container-runtime_%.bbappend
- layers/meta-balena-jetson/recipes-containers/nvidia-container-toolkit/nvidia-container-toolkit_%.bbappend
Poky Dunfell is using Go v1.14 while meta-balena is still in v1.12. The -trimpath flag is introduced in v1.13 so we need to remove it from the build flags for the time being.
Poky defaulted to using -trimpath in commit 2d0c2242136e8c823d58218844c6e082122d0bce
> Fix nvidia container runtime/toolkit to build with GO v1.12

- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra/0001-Enable-SPI1.patch
- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
- Update BalenaOS to 2.69.1
- Enable spi1 by default
> Update BalenaOS to 2.69.1

- layers/meta-balena-jetson/conf/machine/photon-nano.conf
This sets the default ASPM policy for PCIe devices on photon-nano to fix some wifi adapters.
Some adapters seem to fail when entering a powersave state when initializing. For example an Intel 8265 adapter [as reported by @EdjeElectronics](https://github.com/balena-os/balena-jetson/pull/132#issuecomment-780595215):
```
[   70.955113] iwlwifi 0000:01:00.0: Detected Intel(R) Dual Band Wireless AC 8265, REV=0x230
[   70.957583] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[   70.958432] iwlwifi 0000:01:00.0: L1 Enabled - LTR Enabled
[   76.153451] iwlwifi 0000:01:00.0: Failed to load firmware chunk!
[   76.159584] iwlwifi 0000:01:00.0: Could not load the [1] uCode section
[   76.191459] iwlwifi 0000:01:00.0: Failed to start INIT ucode: -110
[   76.243629] WARNING: CPU: 1 PID: 8667 at …
```
> Set ASPM policy for photon-nano to fix PCIe wifi devices

- layers/meta-balena-jetson/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
We add these in the device repository since
these are needed for the TX2 only and we don't
want to take up space on devices where these
aren't needed.
Changelog-entry: packagegroups: Add Ath10k and qca firmwares for TX2
> packagegroups: Add Ath10k and qca firmwares for TX2

- floyd-nano.coffee
Changelog-entry: floyd-nano: Mark board as community device
> floyd-nano: Mark board as community device

- layers/meta-balena-jetson/conf/machine/jn30b-nano.conf
- layers/meta-balena-jetson/conf/machine/photon-nano.conf
- layers/meta-balena-jetson/recipes-bsp/tegra-binaries/files/resinOS-flash210.xml
- layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra210-flash_32.4.4.bb
- layers/meta-balena-jetson/recipes-core/images/balena-image.inc
- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-nano
- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-xavier-nx-devkit
This is a WIP PR and it currently only covers the Nano SD and Nano eMMC modules boot blob stored either on the qspi-nor or on the emmc hw partition.
Addresses: https://github.com/balena-os/balena-jetson/issues/170
> [WIP] Nano generate bootblob for 32.4.4

- layers/meta-balena-jetson/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
These were needed to deliver an urgent OS image,
now meta-balena updates the firmware recipe so
we can drop these changes.
This reverts commit e96dc8e because it is no longer
necessary.
Changelog-entry: linux-firmware: drop temporary fw update changes
> linux-firmware: drop temporary fw update changes

- layers/meta-balena-jetson/recipes-core/images/balena-image-initramfs.bbappend
- layers/meta-balena-jetson/recipes-core/images/balena-image.inc
- layers/meta-balena-jetson/recipes-core/initrdscripts/files/governor
- layers/meta-balena-jetson/recipes-core/initrdscripts/initramfs-framework_%.bbappend
- layers/meta-balena-jetson/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra/0001-dont-export-rpmb-as-part.patch
- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
Commit https://github.com/balena-os/balena-jetson/pull/195/commits/338c6eacdf40cf9618b7659bd31882dc58bbefcd adds backported qmi_wwan patches to all boards in this repository - related to https://github.com/balena-os/balena-jetson/issues/178.
> Release v2.82.8

- layers/meta-balena-jetson/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
We only needed this for one release, until the firmware update
in meta-balena is merged.
Changelog-entry: linux-firmware: Revert update to latest upstream head revision
> linux-firmware: Revert update to latest upstream head revision

- jetson-tx2-nx-devkit.coffee
Unlike the TX2, the TX2 NX does not have a flasher image,
which means the boot partition is not the first one in the
table. Set the index to 24 so that the image-maker knows
where to place the configuration files.
Changelog-entry: jetson-tx2-nx-devkit: Specify actual boot partition index
> jetson-tx2-nx-devkit: Specify actual boot partition index

- layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra194-nxde-flash-dry_32.5.1.bb
- layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra194-nxde-sdcard-flash_32.5.1.bb
- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-xavier-nx-devkit
Update balena-yocto-scripts from 1.14.7 to 1.14.8
Changelog-entry: Update balena-yocto-scripts from v1.14.7 to v1.14.8
We also fixed config.json placing in the last build for the tx2 nx so now we need a new image deploy for testing dashboard
triggered hup on this new device release. We'll use this PR for that.
> balena-yocto-scripts: Update to v1.14.8

- layers/meta-balena-jetson/conf/samples/local.conf.sample
Update the sample configuration file to use OS_DEVELOPMENT instead of DEVELOPMENT_IMAGE.
Change-type: patch
Changelog-entry: meta-balena-jetson: update local.conf.sample
Signed-off-by: Mark Corbin <mark@balena.io>
> meta-balena-jetson: update local.conf.sample

- jetson-nano-2gb-devkit.coffee
- jetson-nano.coffee
It is reported that newer units come with the qspi memory
pre-flashed with bootloaders that cannot run the BalenaOS image.
Update the flashing instructions to recommend Jetson Flash,
which writes both the image on the sd-card in the nano and
the qspi flash, so that they match and boot the BalenaOS
SD-CARD image.
> Update provisioning steps for Jetson Nano SD-CARD and 2GB SD-CARD

- layers/meta-balena-jetson/conf/layer.conf
- layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra194-nxde-sdcard-flash_32.6.1.bb
- layers/meta-balena-jetson/recipes-bsp/tools/tegra-boot-tools_%.bbappend
- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra/0001-tegra-defconfig-Use-PMIC-WDT.patch
- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
We do so to overcome a very sporadic hang in cboot 32.6.1 which appears
to happen sometimes when cboot cannot detect partition on the SD-CARD.
This appears to happen very seldom, right after a reboot, thus we enable
PMIC WDT to reboot the device in this case.
Connects-to: https://github.com/OE4T/meta-tegra/issues/891#issuecomment-1027875304
> Enable PMIC WDT on Xavier NX SD

- layers/meta-balena-jetson/recipes-bsp/tegra-binaries/files/tx2_28_x_hook_fix.sh
- layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra186-flash-dry_32.6.1.bb
- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/50-resin-bootfiles-jetson-tx2
In this commit we improve the old update hook that exists in L4T 28.X
based systems to allow reverting to the old 28.x partition layout.
Images that were releases on L4T 28.1, 28.2 etc did not support re-creating
the partition layout in case of a rollback, because the new 32.X layout
was not known at that point, and we were not aware that there could
be situations in which connectivity problems could cause the system
to roll back to an inconsistent state.
We therefore fix this, so in case the new L4T 32.6 based OS encounters
connectivity or engine related issues and rolls back, the updated hook
in the old OS re-writes the partition layout in the corresponding 28.x format,
with the offsets expected by the old tegra-bootloaders, thus allowing the
system to fully revert to the old OS. …
> hostapp-update-hooks: improve health rollbacks to older images

- layers/meta-balena-jetson/recipes-core/images/balena-image.inc
At this moment this is only shipped for the NX devkit but the M.2 module can be plugged to any TX2 board that exposes the slot.
> balena-image.inc: move rtl8822 module and firmware to TX2

- layers/meta-balena-jetson/recipes-core/initrdscripts/files/blockdev
Starting with 32.7.1 the Xavier AGX needs a delay
for the partitions to enumerate after rereadpt
is triggered.
Changelog-entry: Allow for partitions to enumerate right after provisioning
> blockdev: Allow for partitions to enumerate right after provisioning

- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
Changelog-entry: linux-tegra: Enable NFSv4 config
Addreses: https://github.com/balena-os/balena-jetson/issues/353
> linux-tegra: Enable NFSv4 config

- layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
Connects-to: https://github.com/balena-os/balena-jetson/issues/353
Changelog-entry: linux-tegra: Enable NFS V4 server support
> linux-tegra: Enable NFS V4 server support

- jetson-tx1.coffee
The `state` field in device-type.json is no longer used by the cloud,
it's enough to set the hostapp as `is_archived`.
However, until we stop using device-type.json it would be confusing not
to update the state field.
Changelog-entry: Flag jetson-tx1 as discontinued
Signed-off-by: Alex Gonzalez <alexg@balena.io>
> jetson-tx1: Flag as discontinued

- layers/meta-balena-jetson/conf/samples/bblayers.conf.sample
Yocto classes and conf files ignore layer priorities and are parsed
in order instead.
Changelog-entry: Modify layer ordering
Signed-off-by: Alex Gonzalez <alexg@balena.io>
> bblayers: Modify layer ordering

- layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra194-flash-dry_32.7.2.bb
- layers/meta-balena-jetson/recipes-core/images/balena-image.inc
- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-xavier
The kernel blob has been stored in the boot partition since long ago, but it has increased in size so we now need to store it in the rootfs.
Changelog-entry: meta-balena-jetson: Move kernel signed binary to rootfs
> meta-balena-jetson: Move kernel signed binary to rootfs

- floyd-nano.coffee
This DT has not been maintained by the contributor since support was added. Marking it as discontinued as per internal discussion https://balena.zulipchat.com/#narrow/stream/345889-loop.2Fbalena-os/topic/Floyd.20Nano/near/315939998
Changelog-entry: floyd-Nano: Discontinue device type
> floyd-Nano: Discontinue device type

- blackboard-tx2.coffee
- n310-tx2.coffee
These boards do not have any platform
registrations and have not been maintained
by contributors for more than 6 months.
Internal discussion: https://balena.zulipchat.com/#narrow/stream/345889-loop.2Fbalena-os/topic/Floyd.20Nano/near/322934815
Changelog-entry: Discontinue Blackboard TX2 and N310 TX2
> Discontinue Blackboard TX2 and N310 TX2

- layers/meta-balena-jetson/conf/samples/bblayers.conf.sample
Perl is required for building efitools used for
EFI boot entry configuration and secure boot,
Changelog-entry: add meta-perl to bblayers.conf
Signed-off-by: Alex Gonzalez <alexg@balena.io>
> bblayers.conf.sample: add meta-perl

- layers/meta-balena-jetson/recipes-core/images/balena-image-initramfs.bbappend
The Jetson family does not have enough space to increase the initramfs size and the recovery functionality does not fit in the current maximum space allocation of 32MB.
Changelog-entry: remove recovery module from balena-image-initramfs
> balena-image-initramfs: remove recovery module

- layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/50-resin-bootfiles-jetson-tx2
On a dfferent type of CDS devices, the state symlink to the mts-bootpack partition may be present when hup starts but later when dd is used to calculate the md5sum they were removed
It's possible that udev repopulates the /dev/disk/by- directories, so let's check if the initial symlink disappeared and perform a couple retries if it did, to see if it gets re-created or can be obtained from the partlabel directory.
At most, if none of the symlinks exist anymore the update will fail and the hooks from the previous OS will run. The update should be re-triggered from the API in this case. We also set errexit because devices running on 28.x should have been updated to a previous release at this point.
Fixes https://github.com/balena-os/balena-jetson/issues/601
Changelog-entry: …
> hostapp-update-hooks: Improve state symlinks checks

- layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra-bootfiles_32.7.3.bbappend
tegra194-a02-bpmp-p2888-a04.dtb should be modified instead of tegra194-a02-bpmp-p2888-a01.dtb
Changelog-entry: tegra-bootfiles: Modify can parents for a04 bpmp for Xavier AGX
> tegra-bootfiles: Modify can parents for a04 bpmp on Xavier AGX

- layers/meta-balena-jetson/recipes-connectivity/networkmanager/files/50-sample-script
- layers/meta-balena-jetson/recipes-connectivity/networkmanager/networkmanager_%.bbappend
- layers/meta-balena-jetson/recipes-core/images/balena-image.bbappend
- layers/meta-balena-jetson/recipes-core/images/balena-image.inc
This is needed for jetson-flash so it can populate other scripts potentially added by users.
Fixes test failure and allows merging of https://github.com/balena-os/jetson-flash/pull/127 once a production image of jetson-tx2 is available with these changes included.
> Add sample NM dispatcher script

- layers/meta-balena-jetson/recipes-core/images/balena-image-initramfs.bbappend
Recent updates in the migrate module has increased its size and it makes the kernel no longer fit in the boot partition of the TX2.
Trying to merge https://github.com/balena-os/meta-balena/pull/3678/commits we see:
```
ERROR: balena-image-flasher-1.0-r0 do_resin_boot_dirgen_and_deploy: resin-boot: Not enough space for atomic copy operations.
ERROR: balena-image-flasher-1.0-r0 do_resin_boot_dirgen_and_deploy: ExecutionError('/home/alexgg/balena-jetson/build/tmp/work/jetson_tx2-poky-linux/balena-image-flasher/1.0-r0/temp/run.do_resin_boot_dirgen_and_deploy.1941646', 1, None, 
None)                                                                                                                 
ERROR: Logfile of failure stored in: /home/alexgg/balena-jetson/build/tmp/work/jetson_tx2-poky-linux …
```
> balena-image-initramfs: remove migrate module for jetson-tx2
